package br.com.acs.Models.Enum;

public enum MaterialConstrucao {

    ALVENARIA_COM_REVESTIMENTO, ALVENARIA_SEM_REVESTIMENTO, TAIPA_COM_REVESTIMENTO,
    TAIPA_SEM_REVESTIMENTO, PALHA, MADEIRA_APARELHADA, MATERIAL_APROVEITADO,
    OUTRO
}
